# Generated by Django 4.1.6 on 2023-02-24 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phoneNo', models.IntegerField()),
                ('address', models.TextField()),
                ('designation', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Tester', 'Tester')], max_length=200)),
                ('employee_image', models.ImageField(upload_to='employeeimg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
