# Generated by Django 4.1.6 on 2023-02-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_remove_employee_user_alter_employee_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phoneNo',
            field=models.CharField(max_length=10),
        ),
    ]
